# Generated by Django 4.1 on 2024-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='lognote',
            field=models.CharField(default='create', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
