# Generated by Django 4.1 on 2024-01-09 11:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descript', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reject', 'Rejected'), ('pending', 'Pending'), ('complete', 'Complete')], default='open', max_length=50)),
                ('startingdate', models.DateTimeField(verbose_name='date published')),
                ('completeddate', models.DateTimeField(blank=True, null=True)),
                ('DueDate', models.DateTimeField(blank=True, null=True)),
                ('addeddate', models.DateTimeField(verbose_name='date published')),
                ('removedate', models.DateTimeField(blank=True, null=True)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.priority')),
                ('staffadd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_addedstaff', to=settings.AUTH_USER_MODEL)),
                ('staffdelete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_deletedstaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descript', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descript', models.CharField(max_length=1024)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('addeddate', models.DateTimeField(verbose_name='date published')),
                ('removedate', models.DateTimeField(blank=True, null=True)),
                ('staffadd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_addedstaff', to=settings.AUTH_USER_MODEL)),
                ('staffdelete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_deletedstaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addeddate', models.DateTimeField(verbose_name='date published')),
                ('removedate', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.projects')),
                ('staffadd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_addedstaff', to=settings.AUTH_USER_MODEL)),
                ('staffassign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffassigned', to=settings.AUTH_USER_MODEL)),
                ('staffdelete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_deletedstaff', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.projects')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.type'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lognote', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('complete', 'Completed')], default='create', max_length=200)),
                ('addeddate', models.DateTimeField(verbose_name='date published')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.projects')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
