# Generated by Django 4.1 on 2024-01-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0002_alter_log_lognote_alter_projects_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignto',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=200),
        ),
    ]
