# Generated by Django 4.1 on 2024-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0002_priority_projects_type_tasks_taskassignto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstasks',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignto',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
