# Generated by Django 4.1 on 2024-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0003_projects_isdeleted_projectstasks_isdeleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='startingdate',
        ),
        migrations.AlterField(
            model_name='projects',
            name='addeddate',
            field=models.DateTimeField(editable=False, verbose_name='date published'),
        ),
    ]
