# Generated by Django 4.1 on 2024-01-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0003_alter_taskassignto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editeddate', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('mainproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_project', to='projectsmanager.projects')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_project', to='projectsmanager.projects')),
            ],
        ),
    ]
