# Generated by Django 4.1 on 2024-01-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0004_remove_projects_startingdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.tasks'),
        ),
        migrations.AddField(
            model_name='taskassignto',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='addeddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='addeddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='taskassignto',
            name='addeddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='addeddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
