# Generated by Django 4.1 on 2024-01-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsmanager', '0005_remove_tasks_status_log_task_taskassignto_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, default='Null', null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsmanager.tasks'),
        ),
    ]
